# sync_intent.py
from __future__ import annotations

import os
from pathlib import Path

import click
import httpx
from dotenv import load_dotenv

load_dotenv()

KB_PROFILE = "d9ee3048-f3db-4571-a682-8e29aebecaa2"       # Profile & Evidence
KB_POSITIONING = "4e6a42dd-582f-4347-bc0a-79aa60f1951a"   # Positioning & Narrative


def fetch_findings(supabase_url: str, service_key: str, kb_id: str,
                   timeout: float = 30.0) -> list[dict]:
    """Read findings for one KB via PostgREST (service-role, RLS bypassed, scoped
    explicitly by kb_id — mirrors delapan's own service-client convention)."""
    resp = httpx.get(
        f"{supabase_url.rstrip('/')}/rest/v1/findings",
        headers={"apikey": service_key, "Authorization": f"Bearer {service_key}"},
        params={"kb_id": f"eq.{kb_id}", "select": "title,content,category"},
        timeout=timeout,
    )
    resp.raise_for_status()
    return resp.json()


def render_intent(profile: list[dict], positioning: list[dict]) -> str:
    def block(rows: list[dict]) -> str:
        parts = []
        for r in rows:
            title = r.get("title", "").strip()
            content = (r.get("content") or "").strip()
            parts.append(f"### {title}\n{content}" if title else content)
        return "\n\n".join(parts)

    return (
        "# Candidate Intent\n\n"
        "> Generated by sync_intent.py from the delapan KB. Human-editable.\n\n"
        "## Profile & Evidence\n\n" + block(profile) + "\n\n"
        "## Positioning & Narrative\n\n" + block(positioning) + "\n"
    )


@click.command()
@click.option("--out", "out_path", default="intent.md", type=Path)
def main(out_path: Path) -> None:
    url = os.getenv("SUPABASE_URL")
    key = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
    if not url or not key:
        raise SystemExit("SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY required.")
    profile = fetch_findings(url, key, os.getenv("KB_PROFILE_ID", KB_PROFILE))
    positioning = fetch_findings(url, key, os.getenv("KB_POSITIONING_ID", KB_POSITIONING))
    out_path.write_text(render_intent(profile, positioning), encoding="utf-8")
    click.echo(f"Wrote {out_path} — {len(profile)} profile + "
               f"{len(positioning)} positioning findings.")


if __name__ == "__main__":
    main()
